<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="10" ignored="1" total="11" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="240534" started-at="2018-12-21T12:52:42Z" finished-at="2018-12-21T12:56:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="240534" started-at="2018-12-21T12:52:42Z" finished-at="2018-12-21T12:56:42Z">
      <class name="com.ofs.training.java.test.ServicePersonTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="init" is-config="true" duration-ms="11" started-at="2018-12-21T12:52:42Z" finished-at="2018-12-21T12:52:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="312" started-at="2018-12-21T12:52:42Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:52:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=ramachandran, last_name=shankar, email=ram@gmail.com, address_id=17, birth_date=1996-08-14, created_date=2018-12-21, address=PojoServiceAddress [id=17, street=sainagar, city=chennai, postal_code=668779], getId()=0, getFirst_name()=ramachandran, getLast_name()=shankar, getEmail()=ram@gmail.com, getAddress_id()=17, getBirth_date()=1996-08-14, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=17, street=sainagar, city=chennai, postal_code=668779], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=2092769598, toString()=com.ofs.training.java.pojo.PojoServicePerson@7cbd213e]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=1, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=1, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=422392391, toString()=com.ofs.training.java.pojo.PojoServicePerson@192d3247]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="36" started-at="2018-12-21T12:52:42Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:52:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=ajith, last_name=sekar, email=ajith@gmail.com, address_id=18, birth_date=1995-02-17, created_date=2018-12-21, address=PojoServiceAddress [id=18, street=vallalarnagar, city=salem, postal_code=877979], getId()=0, getFirst_name()=ajith, getLast_name()=sekar, getEmail()=ajith@gmail.com, getAddress_id()=18, getBirth_date()=1995-02-17, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=18, street=vallalarnagar, city=salem, postal_code=877979], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1896294051, toString()=com.ofs.training.java.pojo.PojoServicePerson@710726a3]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=2, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=2, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1684015092, toString()=com.ofs.training.java.pojo.PojoServicePerson@646007f4]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30005" started-at="2018-12-21T12:52:42Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:53:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=durai, last_name=raj, email=durai@gmail.com, address_id=0, birth_date=1958-07-15, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=karunaistreet, city=vellore, postal_code=748868], getId()=0, getFirst_name()=durai, getLast_name()=raj, getEmail()=durai@gmail.com, getAddress_id()=0, getBirth_date()=1958-07-15, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=karunaistreet, city=vellore, postal_code=748868], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1418385211, toString()=com.ofs.training.java.pojo.PojoServicePerson@548ad73b]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=3, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=3, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1282811396, toString()=com.ofs.training.java.pojo.PojoServicePerson@4c762604]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30005" started-at="2018-12-21T12:53:12Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:53:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=ganesh, last_name=chandran, email=gan@gmail.com, address_id=0, birth_date=1887-06-18, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=chandranagar, city=trichy, postal_code=676868], getId()=0, getFirst_name()=ganesh, getLast_name()=chandran, getEmail()=gan@gmail.com, getAddress_id()=0, getBirth_date()=1887-06-18, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=chandranagar, city=trichy, postal_code=676868], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1883840933, toString()=com.ofs.training.java.pojo.PojoServicePerson@704921a5]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=4, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=4, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=233996206, toString()=com.ofs.training.java.pojo.PojoServicePerson@df27fae]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30010" started-at="2018-12-21T12:53:42Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:54:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=jai, last_name=ravi, email=jai@gmail.com, address_id=0, birth_date=1767-04-04, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=faraznagar, city=chennai, postal_code=667645], getId()=0, getFirst_name()=jai, getLast_name()=ravi, getEmail()=jai@gmail.com, getAddress_id()=0, getBirth_date()=1767-04-04, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=faraznagar, city=chennai, postal_code=667645], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=832279283, toString()=com.ofs.training.java.pojo.PojoServicePerson@319b92f3]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=5, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=5, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=265119009, toString()=com.ofs.training.java.pojo.PojoServicePerson@fcd6521]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30006" started-at="2018-12-21T12:54:12Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:54:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=praveen, last_name=sabari, email=praveen@gmail.com, address_id=0, birth_date=1552-06-27, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=kannanstreet, city=kovai, postal_code=682697], getId()=0, getFirst_name()=praveen, getLast_name()=sabari, getEmail()=praveen@gmail.com, getAddress_id()=0, getBirth_date()=1552-06-27, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=kannanstreet, city=kovai, postal_code=682697], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1434041222, toString()=com.ofs.training.java.pojo.PojoServicePerson@5579bb86]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=6, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=6, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1375995437, toString()=com.ofs.training.java.pojo.PojoServicePerson@5204062d]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30007" started-at="2018-12-21T12:54:42Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:55:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=harish, last_name=gopi, email=hari@gmail.com, address_id=0, birth_date=1975-08-06, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=tanishnagar, city=chennai, postal_code=576988], getId()=0, getFirst_name()=harish, getLast_name()=gopi, getEmail()=hari@gmail.com, getAddress_id()=0, getBirth_date()=1975-08-06, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=tanishnagar, city=chennai, postal_code=576988], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1561408618, toString()=com.ofs.training.java.pojo.PojoServicePerson@5d11346a]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=7, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=7, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=2050404090, toString()=com.ofs.training.java.pojo.PojoServicePerson@7a36aefa]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30005" started-at="2018-12-21T12:55:12Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:55:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=vignesh, last_name=tharma, email=vig@gmail.com, address_id=0, birth_date=1716-04-03, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=pawannagar, city=chittur, postal_code=857568], getId()=0, getFirst_name()=vignesh, getLast_name()=tharma, getEmail()=vig@gmail.com, getAddress_id()=0, getBirth_date()=1716-04-03, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=pawannagar, city=chittur, postal_code=857568], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=282432134, toString()=com.ofs.training.java.pojo.PojoServicePerson@10d59286]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=8, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=8, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=266437232, toString()=com.ofs.training.java.pojo.PojoServicePerson@fe18270]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30005" started-at="2018-12-21T12:55:42Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:56:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=giri, last_name=dharan, email=giri@gmail.com, address_id=0, birth_date=1664-04-14, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=gurustreet, city=erode, postal_code=681686], getId()=0, getFirst_name()=giri, getLast_name()=dharan, getEmail()=giri@gmail.com, getAddress_id()=0, getBirth_date()=1664-04-14, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=gurustreet, city=erode, postal_code=681686], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=1381128261, toString()=com.ofs.training.java.pojo.PojoServicePerson@52525845]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=9, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=9, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=999609945, toString()=com.ofs.training.java.pojo.PojoServicePerson@3b94d659]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
        <test-method status="FAIL" signature="testCreate_positive(com.ofs.training.java.pojo.PojoServicePerson, com.ofs.training.java.pojo.PojoServicePerson)[pri:1, instance:com.ofs.training.java.test.ServicePersonTest@10bdf5e5]" name="testCreate_positive" duration-ms="30008" started-at="2018-12-21T12:56:12Z" data-provider="testCreate_positive" finished-at="2018-12-21T12:56:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PojoServicePerson [id=0, first_name=samuel, last_name=praveen, email=sam@gmail.com, address_id=0, birth_date=1865-06-12, created_date=2018-12-21, address=PojoServiceAddress [id=0, street=laxstreet, city=kanchi, postal_code=586899], getId()=0, getFirst_name()=samuel, getLast_name()=praveen, getEmail()=sam@gmail.com, getAddress_id()=0, getBirth_date()=1865-06-12, getCreated_date()=2018-12-21, getAddress()=PojoServiceAddress [id=0, street=laxstreet, city=kanchi, postal_code=586899], getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=900008524, toString()=com.ofs.training.java.pojo.PojoServicePerson@35a50a4c]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PojoServicePerson [id=10, first_name=null, last_name=null, email=null, address_id=0, birth_date=null, created_date=null, address=null, getId()=10, getFirst_name()=null, getLast_name()=null, getEmail()=null, getAddress_id()=0, getBirth_date()=null, getCreated_date()=null, getAddress()=null, getClass()=class com.ofs.training.java.pojo.PojoServicePerson, hashCode()=520232556, toString()=com.ofs.training.java.pojo.PojoServicePerson@1f021e6c]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ofs.training.java.test.ServicePersonTest.testCreate_positive(ServicePersonTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate_positive -->
      </class> <!-- com.ofs.training.java.test.ServicePersonTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
